name: Greetings

on: [pull_request_target, issues]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi!👋\nThank you for raising the issue.\nI hope, the plugin makes your workflow easier!\nWe will take a look to your issue as soon as possible.💖"
        pr-message: "Hi!👋\nThank you for the Pull Request 💖.\nPlease read [CONTRIBUTING.md](https://github.com/ilyachur/cmake4vim/blob/master/CONTRIBUTING.md) to make a good PR."
