name: Post CI

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ master ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-workflow-run-wait@v1
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      with:
          name: coverage
          path: ./cov_report
    - name: Upload coverage to Codecov
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN  }}
      run: |
        bash <(curl -s https://codecov.io/bash) $(echo \ `ls -d ./cov_report/*` | sed -r 's/ / -f /g') -Z
    - name: Upload coverage to Codecov
      if: ${{ github.event.workflow_run.conclusion != 'success' }}
      run: |
        echo ${{ github.event.workflow_run.conclusion }}
        exit 1
