name: Windows

on: [push]

jobs:
  run:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rhysd/action-setup-vim@v1
    - name: Setup python modules
      uses: actions/setup-python@master
      with:
          python-version: 3.7
    - name: Install covimerage
      run: |
          pip3 install covimerage --user
          pip3 install coveralls --user

    - name: Run tests
      shell: cmd
      run: |
        ./test/local_run.bat

    - name: Generate coverage report
      run: |
          python -m covimerage write_coverage vim-profile.txt
          python -m coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN  }}
          file: ./coverage.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true
